### ISSUE TITLE
registration & log-in die or generate error

### ISSUE THREAD

**Issue by EricLScace** [squad-three/squad-three-front-end#37]
You may have to change some config to reflect the Heroku instance

Check this: https://github.com/squad-three/squad-three-back-end/wiki/Guide-for-deploying-code-to-public-front-and-back-end-servers

**Comment by lisawilliams** [comment]
Eric: if your problem is that you are trying to do login and it's failing, I think the problem may be in the front end repo, not the back end repo.  This is the config for the front end repo:

```'use strict'

const config = {
  apiOrigins: {
    production: 'https://ga-wdi-boston.herokuapp.com'
  }
}

module.exports = config
```

That's clearly not right. We need our localhost server (4741) for apiOrigins.development (which is entirely missing) and https://enigmatic-beyond-36967.herokuapp.com/ for our apiOrigins.production.   Would you agree?   I'm not sure where you are trying to reach the Heroku instance API from -- through a curl script, or through running localhost, or through the deployed? This problem would actually affect pretty much everything except a curl script run directly on the back end server.
